spring:
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/light_chaser_server?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
      username: root
      password: qq123123




# mybatis-plus配置
mybatis-plus:
  type-aliases-package: com.dagu.lightchaser.entity
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


light-chaser:
  project-resource-path: /D:/project/light-chaser-server # 项目资源路径
  source-image-path: /images/ # 源图片路径
  cover-path: /covers/ # 封面路径
  migration: # 是否自动跑sql脚本
    enable: true

logging:
  config: classpath:log4j2-spring.xml
  level:
    cn.jay.repository: trace
